server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://caatingadb.cdnf5asglmrk.sa-east-1.rds.amazonaws.com:5432/caatingadb
    username: hilbert
    password: Di##7890
    pool-size: 30